org: seanmngan
app: hattavick-backend
service: hattavick-backend
	
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
    environment:
      MONGO_USER: ${ssm:/hattavick/mongo/user}
      MONGO_PASSWORD: ${ssm:/hattavick/mongo/password}
